#!/bin/sh

. ./tmake.sh

tmake_init "$@"

# list of all commands
# keep this in alphabetic order
CMDS="[ \
	basename \
	cat \
	chmod \
	chown \
	clear \
	cp \
	dd \
	dirname \
	echo \
	false \
	find \
	gunzip \
	gzip \
	head \
	hex \
	id \
	ln \
	ls \
	mkdir \
	mv \
	pwd \
	readlink \
	realpath \
	rm \
	rmdir \
	seq \
	sleep \
	stat \
	test \
	touch \
	tr \
	true \
	unlink \
	wc \
	which \
	whoami \
	xargs\
	yes \
	zcat"

echo "
LN_S ?= ln -s
" >> "$MAKEFILE"

tmake_add_executable "tutils" src/*.c CFLAGS="-Iinclude"
echo "
.PHONY : install-symlinks
install : install-symlinks
install-symlinks : install-tutils" >> "$MAKEFILE"

for CMD in $CMDS ; do
	echo "	@echo \"LN_S tutils \$(DESTDIR)\$(PREFIX)/bin/$CMD\"
	\$(Q)\$(LN_S) -f \"tutils\" \"\$(DESTDIR)\$(PREFIX)/bin/$CMD\""
done >> "$MAKEFILE"

tmake_fini
